# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: convert.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rconvert.proto\"\x1a\n\x08\x43urrency\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x32\x31\n\tConverter\x12$\n\nconvertUSD\x12\t.Currency\x1a\t.Currency\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'convert_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CURRENCY._serialized_start=17
  _CURRENCY._serialized_end=43
  _CONVERTER._serialized_start=45
  _CONVERTER._serialized_end=94
# @@protoc_insertion_point(module_scope)
